### ISSUE TITLE
Add highlighting for .gitattributes/.gitignore files

### ISSUE THREAD

**Issue by Alhadis** [atom/language-git#11]
This was suggested in a previous issue (atom/language-git#2), but the consensus was that `.gitignore` files are only peripherally related to Git, and are better handled by a more dedicated package like `language-ignore` or something.

Would `.gitattributes` files not fall within the scope of this package, then? As far as Git-related grammar goes, they (along with `.gitignore`) play a pretty integral part of repository management. I don't think lumping their highlighting in along with `.gitconfig` is going to be passed off as unusual.

**Comment by ldez** [comment]
I have created a package [language-ignore](https://atom.io/packages/language-ignore) with the support of `.gitignore`, `.npmignore`, `.coffeelintignore` and `.slugignore`.
If this can help.

**Comment by Alhadis** [comment]
Oh crap, I should've closed this issue after I discovered [this package](https://github.com/lee-dohm/language-generic-config). My bad!

**Comment by ldez** [comment]
I have created an another package [language-gitattributes](https://atom.io/packages/language-gitattributes) with the support of `.gitattributes`.
Colorful syntax!
