### ISSUE TITLE
.gitignore ! negation rules not processed properly

### ISSUE THREAD

**Issue by danielfarrell** [atom/language-git#24]
We have a client project we are helping on that has a nested `.gitignore` file with these contents:

```
*.*
!.gitignore
!/javascripts/**
```

It is supposed to be ignore everything in here except the `.gitignore` and everything in `/javascripts/`, which git seems to handle properly, but atom does not.  It is showing everything in `/javascripts/` as ignored.  I'll try to figure out where that handling is done and make a PR, but thought I'd make the issue first in case someone already knows the code and knows why that would happen.

**Comment by 50Wliu** [comment]
The language-git package is unrelated to Atom's git integration.  All it does is provide syntax highlighting for Git-related files.

You probably want to report this on the tree-view or atom/atom repo instead.
