### ISSUE TITLE
Special "light" mode for fast git start

### ISSUE THREAD

**Issue by rugk** [atom/language-git#25]
I would really like to use Atom for editing commit messages of git, however I have one big problem: With a lot of packages installed Atom is just _veery_ slow.

This is why I'd propose to add a special `git-start` mode of Atom. This is how it should work:
When Atom is already started it should just work as usual, opening a new tab and let the user type in the commit message.
However when Atom is not already started it should just load a "light" version of Atom, where it does only load Atom (& most core packages) and `language-git` (and possibly some packages the user can configure manually), but not anything else. The reason is simple: In 80% of these situation the user will close Atom anyway directly after finishing writing the commit message, so there is not need to load packages for Python, PHP or so...

Of course it would be awesome if a user could load the missing packages afterwards when they finished writing the commit message, so that they can even go on using Atom without having to restart it.

**Comment by 50Wliu** [comment]
This belongs on [atom/atom](https://github.com/atom/atom), not here.

**Comment by rugk** [comment]
Okay, moved there: https://github.com/atom/atom/issues/12607
