### ISSUE TITLE
Unwanted title length warning highlighting in message

### ISSUE THREAD

**Issue by mmore500** [atom/language-git#26]
When editing COMMIT_EDITMSG files, I get unwanted red highlighting on my commit message (not just the title). I am using atom 1.10.2 on macOs Sierra.
<img width="599" alt="unwanted_highlighting" src="https://cloud.githubusercontent.com/assets/10763333/18806657/0cc22be0-81e8-11e6-88c8-a24ec4edba8d.png">

**Comment by lucascosti** [comment]
@mmore500 Was this issue fixed? I can't see a PR mentioned.

I came here to report the same problem (currently running 1.11.2).

**Comment by lucascosti** [comment]
@50Wliu Can we reopen this issue? The problem is still occurring (I can create a new issue if you think that is better)

**Comment by 50Wliu** [comment]
@lucascosti Opening a new issue would be better, thanks.
