### ISSUE TITLE
Diff syntax is parsing in a wrong way for lua comments

### ISSUE THREAD

**Issue by actionless** [atom/language-git#3]
please see attached screenshot
![2014-07-20--1405883204_1600x900_scrot](https://cloud.githubusercontent.com/assets/1655669/3638305/637cd2ba-1042-11e4-99c4-34be86da6a7e.png)

**Comment by kevinsawicki** [comment]
This package does not do diff highlighting, I think you must have installed the `language-diff` package which handles `.diff` files, closing this out.
