### ISSUE TITLE
`git config.cson` colors breaks with \"$LOCAL\" \"$REMOTE\" (or is it invalid?)

### ISSUE THREAD

**Issue by GabLeRoux** [atom/language-git#4]
[difftool "diffmerge"]
	    cmd = diffmerge --nosplash \"$LOCAL\" \"$REMOTE\"
	[mergetool "diffmerge"]
	    cmd = diffmerge --nosplash \"$LOCAL\" \"$REMOTE\"
	    trustExitCode = true

result in:

![gitconfigcolors](https://cloud.githubusercontent.com/assets/1264761/6416372/ae18f17a-be73-11e4-99d3-0bf4b1323e9b.png)

This seems to be valid syntax, (maybe I'm wrong) :+1:

**Comment by kevinsawicki** [comment]
Looks like a bug to me
