### ISSUE TITLE
Failed to load a language-git package grammar

### ISSUE THREAD

**Issue by elyaraujo** [atom/language-git#49]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-git](https://github.com/atom/language-git) package 0.19.1

### Stack Trace

Failed to load a language-git package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git config.json' in C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git config.json

Error: ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-git\grammars\git config.json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-git/grammars/git config.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
color-picker 2.0.14 
minimap 4.19.0 
pigments 0.19.5 
```

**Comment by Ilias48rus** [comment]
Atom's installation writing language pascages 's files names using "%20" instead of " ", and they becoming different from patch's in which atom using " ".

**Comment by rsese** [comment]
Closing per https://github.com/atom/language-ruby-on-rails/issues/55#issuecomment-309392781, feel free to subscribe to https://github.com/atom/language-java/issues/94 for updates.
