### ISSUE TITLE
Add ability to customize grammar.

### ISSUE THREAD

**Issue by jacksonrayhamilton** [atom/language-git#65]
It seems like this package is included in Atom as a default language grammar for its built-in Git-commit-message-writing-support feature.  Being a built-in package, I'd expect it to have some fairly uncontroversial default settings.  However, I see that it has some opinions on how I write my commit messages.  I disagree with some of the opinions, e.g. the requirement against ending a commit message with a period.  I'd like to be able to turn some or all of these "lintings" off.  Can we add some options to do that?

**Comment by 50Wliu** [comment]
Thanks for reaching out!

In order to keep the complexity of language grammars as low as possible, and due to the limitations of CSON/JSON in this regard, we will not be adding any options to grammar packages.  If you disagree with some of the conventions, feel free to open new issues asking about why the conventions are included, or fork your own language-git grammar.

**Comment by jacksonrayhamilton** [comment]
Regarding keeping language grammar complexity low, to play devil's advocate, isn't the inclusion of opinionated rules like this increasing the complexity?

Regarding "the limitations of CSON/JSON," what would have to change in this package, or, less desirably, in Atom itself, in order for customizing a grammar to be a reasonable thing to implement?

**Comment by 50Wliu** [comment]
> Regarding keeping language grammar complexity low, to play devil's advocate, isn't the inclusion of opinionated rules like this increasing the complexity?

You could argue that, yes.  However we also believe that it's helpful to point out some best conventions for Git commits.  The current grammar is therefore a balance between no rules and too many rules.  As Atom is fully customizable, you can override the warning styles in your `styles.less` to be the same color as normal text if you wish (or, as per my previous suggestion, create your own fork).

> what would have to change in this package, or, less desirably, in Atom itself, in order for customizing a grammar to be a reasonable thing to implement?

JSON is a format designed for transferring data.  Therefore, no variables are allowed and everything is hardcoded.  To support the level of customization you are asking for, there would need to be one new file for every possible combination of settings.  As that's unfeasible, the required change in Atom core would be to support a way of writing grammars that _does_ support variables.

**Comment by jacksonrayhamilton** [comment]
What if grammars could be specified as modules that export a grammar?

```cs
module.exports = ->
  'name': 'Git Commit Message'
  'patterns': [
    {
      # Subject line 0-50 chars
      'match': '\\A(?!#)(([a-z])|.).{0,48}((\\.)|.)$'
      'captures': Object.assign({},
        if atom.config.get('language-git').shouldCheckCapitalization
          '2':
            'name': 'invalid.illegal.first-char-should-be-uppercase.git-commit'
        ,
        if atom.config.get('language-git').shouldCheckPunctuation
          '4':
            'name': 'invalid.illegal.subject-no-trailing-period.git-commit'
      )
    }
  ]
```
