### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by WalterPonge** [atom/language-git#68]
You have the core package "language-git" installed as a community package. See https://github.com/atom/atom/blob/master/packages/dalek/README.md for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:11:177468)
Generator.next (null:null:null)
step (<embedded>:11:177304)
process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by rsese** [comment]
Thank you for the report!

The readme linked in the report gives you instructions on the steps you need to take to get rid off this deprecation https://github.com/atom/dalek#i-got-a-warning-what-do-i-do
