### ISSUE TITLE
Syntax highlighting not working at all for commit messages

### ISSUE THREAD

**Issue by srinathv** [atom/language-git#9]
I can not get syntax highlighting to work for my commit messages.

<img width="1438" alt="screen shot 2015-07-09 at 2 15 20 pm" src="https://cloud.githubusercontent.com/assets/585481/8605820/0cdb5b7e-2645-11e5-99f6-9154c88ed698.png">

**Comment by lee-dohm** [comment]
It looks like it is working fine. The comment section is darker than the regular type in the other screen. Have you tried putting your cursor in that area and executing the "Editor: Log Cursor Scope" command?

**Comment by srinathv** [comment]
<img width="1272" alt="screen shot 2015-07-16 at 2 51 17 pm" src="https://cloud.githubusercontent.com/assets/585481/8734887/408916d4-2bca-11e5-83f2-b95b30622438.png">

I was expecting the "modified:" line to be orange like the tree view.  Am I wrong?

**Comment by lee-dohm** [comment]
While the scopes are present, it doesn't mean that the theme has to use them. I can't think of a syntax theme that I've used that has colored that section.

**Comment by lee-dohm** [comment]
If you're using the default one-dark-syntax theme, you can file the Issue here:

https://github.com/atom/one-dark-syntax/issues

Let us know if you have any more questions :grinning:
